### PR TITLE
Accept the :caption: option on code-block directives in Sphinx

### PR DESCRIPTION
**Pull request by dependent-type**
Sphinx allows the :caption: option on code-blocks, but doc8 is flagging that as an error.
For instance, this renders fine under Sphinx, but doc8 currently does not like it:

```restructuredtext
.. code-block:: bash
  :caption: doc8 throws an error on caption in code-blocks, even though Sphinx accepts them.

  echo "Let's fix this"
```

This pull request is to change this behavior.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I wonder if there's anyway we can hook into sphinx to simplify some of this. I agree that it'd be nice to have a test case covering this too.

**Comment by dependent-types** [comment]
How would one add a test case for this?

**Comment by ssbarnea** [comment]
Please rebased and add test.

**Comment by ssbarnea** [comment]
ping

**Pull request merged**
